<a href="https://colab.research.google.com/github/sreya-2002/expense-tracker/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("/content/1774404110.csv")

In [4]:
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320

In [5]:
df.shape

(398, 9)

In [6]:
df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [9]:
df[["mpg","weight"]]

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
393  27.0    2790
394  44.0    2130
395  32.0    2295
396  28.0    2625
397  31.0    2720

[398 rows x 2 columns]

In [10]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

missing value (null value)

In [14]:
df.isnull().sum()
     #or
#.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [15]:
print(df["mpg"].min())
print(df["mpg"].max())
print(df["mpg"].mean())
print(df["mpg"].std())

9.0
46.6
23.514572864321607
7.815984312565782

In [16]:
df[df["weight"]==df["weight"].min()]["car name"]

54    datsun 1200
Name: car name, dtype: object

In [20]:
df[df["mpg"]==df["mpg"].max()][["mpg","car name"]]

      mpg   car name
322  46.6  mazda glc

In [21]:
df[df["mpg"]>40]["car name"]

244    volkswagen rabbit custom diesel
309                          vw rabbit
322                          mazda glc
324                         datsun 210
325               vw rabbit c (diesel)
326                 vw dasher (diesel)
329                honda civic 1500 gl
330               renault lecar deluxe
394                          vw pickup
Name: car name, dtype: object

In [22]:
df[(df["mpg"]<40) & (df["mpg"]>30)][["car name","mpg"]]

                              car name   mpg
53                 toyota corolla 1200  31.0
54                         datsun 1200  35.0
129                        datsun b210  31.0
131                toyota corolla 1200  32.0
144                      toyota corona  31.0
..                                 ...   ...
387  oldsmobile cutlass ciera (diesel)  38.0
390                   toyota celica gt  32.0
391                  dodge charger 2.2  36.0
395                      dodge rampage  32.0
397                         chevy s-10  31.0

[76 rows x 2 columns]

In [23]:
new_df=df[["car name","weight"]]
new_df.to_csv("new_df.csv")

In [24]:
new_df=df[["car name","weight"]]
new_df_2=df[["weight","car name"]]

In [25]:
new_df.head(1)

                    car name  weight
0  chevrolet chevelle malibu    3504

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [29]:
df=pd.DataFrame([1,2,3,4], index=[49,48,12,3])

In [30]:
df

    0
49  1
48  2
12  3
3   4

In [31]:
df.loc[49]

0    1
Name: 49, dtype: int64

In [37]:
df.values

array([[1],
       [2],
       [3],
       [4]])